'use strict';(function(){var cmpFile='noModule'in HTMLScriptElement.prototype?'cmp2.js':'cmp2-polyfilled.js';(function(){var cmpScriptElement=document.createElement('script');var firstScript=document.getElementsByTagName('script')[0];cmpScriptElement.async=true;cmpScriptElement.type='text/javascript';var cmpUrl;var tagUrl=document.currentScript.src;cmpUrl='https://cmp.inmobi.com/tcfv2/53/CMP_FILE?referer=makeitmeme.com'.replace('CMP_FILE',cmpFile);cmpScriptElement.src=cmpUrl;firstScript.parentNode.insertBefore(cmpScriptElement,firstScript);})();(function(){var css=""
+" .qc-cmp-button { "
+"   background-color: #457B9D !important; "
+"   border-color: #457B9D !important; "
+" } "
+" .qc-cmp-button:hover { "
+"   border-color: #457B9D !important; "
+" } "
+" .qc-cmp-alt-action, "
+" .qc-cmp-link { "
+"   color: #457B9D !important; "
+" } "
+" .qc-cmp-button.qc-cmp-secondary-button:hover { "
+"   background-color: #457B9D !important; "
+"   border-color: #457B9D !important; "
+" } "
+" .qc-cmp-button { "
+"   color: #FFFFFF !important; "
+" } "
+" .qc-cmp-button.qc-cmp-secondary-button:hover { "
+"   color: #FFFFFF !important; "
+" } "
+" .qc-cmp-button.qc-cmp-secondary-button { "
+"   color: #457B9D !important; "
+" } "
+" .qc-cmp-button.qc-cmp-secondary-button { "
+"   background-color: #F1FAEE !important; "
+"   border-color: transparent !important; "
+" } "
+" .qc-cmp-ui, "
+" .qc-cmp-ui .qc-cmp-title, "
+" .qc-cmp-ui .qc-cmp-table, "
+" .qc-cmp-ui .qc-cmp-messaging, "
+" .qc-cmp-ui .qc-cmp-sub-title, "
+" .qc-cmp-ui .qc-cmp-vendor-list, "
+" .qc-cmp-ui .qc-cmp-purpose-info, "
+" .qc-cmp-ui .qc-cmp-table-header, "
+" .qc-cmp-ui .qc-cmp-beta-messaging, "
+" .qc-cmp-ui .qc-cmp-main-messaging, "
+" .qc-cmp-ui .qc-cmp-vendor-list-title{ "
+"   color: #000000 !important; "
+" } "
+" .qc-cmp-ui a, "
+" .qc-cmp-ui .qc-cmp-alt-action { "
+"   color: #457B9D !important; "
+" } "
+" .qc-cmp-ui { "
+"   background-color: #F1FAEE !important; "
+" } "
+" .qc-cmp-small-toggle.qc-cmp-toggle-on, "
+" .qc-cmp-toggle.qc-cmp-toggle-on { "
+"   background-color: #457B9D!important; "
+"   border-color: #457B9D!important; "
+" } "
+"#qc-cmp2-ui { border-radius: 16px;}#qc-cmp2-ui button { border-radius: 32px; font-weight: bold; font-size: 14px;}#qc-cmp2-ui h2 { font-size: 20px; font-weight: bold;}"
+""
+"";var stylesElement=document.createElement('style');var re=new RegExp('&quote;','g');css=css.replace(re,'"');stylesElement.type='text/css';if(stylesElement.styleSheet){stylesElement.styleSheet.cssText=css;}else{stylesElement.appendChild(document.createTextNode(css));}
var head=document.head||document.getElementsByTagName('head')[0];head.appendChild(stylesElement);})();var autoDetectedLanguage='en';var gvlVersion=3;function splitLang(lang){return lang.length>2?lang.split('-')[0]:lang;};function isSupported(lang){var langs=['en','fr','de','it','es','da','nl','el','hu','pt','pt-br','pt-pt','ro','fi','pl','sk','sv','no','ru','bg','ca','cs','et','hr','lt','lv','mt','sl','tr','zh'];return langs.indexOf(lang)===-1?false:true;};if(gvlVersion===2&&isSupported(splitLang(document.documentElement.lang))){autoDetectedLanguage=splitLang(document.documentElement.lang);}else if(gvlVersion===3&&isSupported(document.documentElement.lang)){autoDetectedLanguage=document.documentElement.lang;}else if(isSupported(splitLang(navigator.language))){autoDetectedLanguage=splitLang(navigator.language);};var choiceMilliSeconds=(new Date).getTime();window.__tcfapi('init',2,function(){},{"coreConfig":{"inmobiAccountId":"4Y2GJKUtJ5Qd-","privacyMode":["GDPR"],"hashCode":"cwnhp+iP8BrkPwFZjUce4Q","publisherCountryCode":"DE","publisherName":"Make it Meme","vendorPurposeIds":[2,4,6,7,9,10,1,3,5,8,11],"vendorFeaturesIds":[1,2,3],"vendorPurposeLegitimateInterestIds":[7,8,9,2,10,11],"vendorSpecialFeaturesIds":[2,1],"vendorSpecialPurposesIds":[1,2],"googleEnabled":true,"consentScope":"service","thirdPartyStorageType":"iframe","consentOnSafari":false,"displayUi":"always","defaultToggleValue":"off","initScreenRejectButtonShowing":false,"initScreenCloseButtonShowing":false,"softOptInEnabled":false,"showSummaryView":true,"persistentConsentLinkLocation":3,"displayPersistentConsentLink":false,"uiLayout":"banner","vendorListUpdateFreq":30,"publisherPurposeIds":[],"initScreenBodyTextOption":1,"publisherConsentRestrictionIds":[],"publisherLIRestrictionIds":[],"publisherPurposeLegitimateInterestIds":[],"publisherSpecialPurposesIds":[],"publisherFeaturesIds":[],"publisherSpecialFeaturesIds":[],"stacks":[],"lang_":autoDetectedLanguage,"gvlVersion":3,"totalVendors":837},"premiumUiLabels":{"initScreenCustomLinks":[{"label":"Privacy Policy","link":"https://makeitmeme.com/privacy"}]},"premiumProperties":{"googleWhitelist":[1]},"coreUiLabels":{},"theme":{"uxPrimaryButtonTextColor":"#FFFFFF","uxPrimaryButtonColor":"#457B9D","uxBackgroundColor":"#F1FAEE","uxSecondaryButtonColor":"#F1FAEE","uxSecondaryButtonTextColor":"#457B9D","uxToogleActiveColor":"#457B9D","uxLinkColor":"#457B9D","uxFontColor":"#000000"},"nonIabVendorsInfo":{"nonIabVendorList":[{"vendorId":3,"pCode":"4Y2GJKUtJ5Qd-","name":"Poki B.V.","description":"Poki B.V. is a platform that offers a variety of online games. They prioritize user privacy and have implemented measures to ensure data protection. While Poki is responsible for the processing of user data in the context of the Poki Website, they also collaborate with game developers and advertising partners. Poki ensures that any third-party content providers comply with applicable data protection laws..","privacyPolicyUrl":"https://poki.com/en/c/privacy-statement","nonIabPurposeConsentIds":[1,8],"nonIabPurposeLegitimateInterestIds":[],"active":null,"gvlVersion":3}]}});})();